version: "2.1"

services:
 db:
  image: wego_carpark_system_db_img
  container_name: wego_carpark_db
  build:
   context: ./database
   dockerfile: Dockerfile
  ports:
   - 3306:3306
  volumes:
    - /home/docker/mysql_data:/var/lib/mysql
  environment:
   MYSQL_DATABASE: "wego_carpark_system"
   MYSQL_USER: "wego"
   MYSQL_PASSWORD: "wego"
   MYSQL_ROOT_PASSWORD: "root"
  healthcheck:
    test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW SCHEMAS;\""
    interval: 3s
    timeout: 1s
    retries: 5
